FROM nginx:latest

COPY ./build/nginx/default.conf /etc/nginx/conf.d/
COPY ./build/nginx/nginx.conf /etc/nginx/

RUN apt update
RUN apt install -y --no-install-recommends \
        python3-acme \
        python3-certbot \
        python3-mock  \
        python3-openssl \
        python3-pkg-resources \
        python3-pyparsing \
        python3-zope.interface \
	nano

RUN apt install -y --no-install-recommends python3-certbot-nginx
